import { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineMapPin,
  HiOutlineRocketLaunch,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
  PiMicrosoftOutlookLogoFill,
} from "react-icons/pi";

import {
  SiJavascript,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
  SiTypescript,
  SiHtml5,
  SiCss3,
  SiSpringboot,
  SiApachemaven,
  SiComma,
  SiSwagger,
  SiPytorch,
  SiTensorflow,
  SiKeras,
  SiScikitlearn,
  SiPandas,
  SiScipy,
  SiSqlite,
  SiPostgresql,
  SiJira,
  SiConfluence,
  SiApachekafka,
  SiKubernetes,
} from "react-icons/si";

import { 
  FaDiscord, 
  FaGithub, 
  FaLinkedin, 
  FaX, 
  FaSpotify, 
  FaYelp, 
  FaInstagram, 
  FaXTwitter, 
  FaFacebook, 
  FaPinterest, 
  FaWhatsapp, 
  FaReddit, 
  FaTelegram, 
  FaJava,
  FaPython,
  FaDatabase,
  FaCode,
  FaReact,
  FaNpm,
  FaAngular,
  FaGitAlt,
  FaBitbucket,
  FaDocker,
  FaFileExcel,
  FaFilePowerpoint,
} from "react-icons/fa6";

import { TbLadle } from "react-icons/tb";
import { FaFileWord, FaNode } from "react-icons/fa";
import { VscVscode } from "react-icons/vsc";
import { GiCycle, GiSpiralTentacle } from "react-icons/gi";
import { ImOnedrive } from "react-icons/im";
import { BsFileBarGraph, BsMicrosoftTeams } from "react-icons/bs";
import { LiaFlagUsaSolid } from "react-icons/lia";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  mapPin: HiOutlineMapPin,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  yelp: FaYelp,
  spotify: FaSpotify,
  instagram: FaInstagram,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  java: FaJava,
  python: FaPython,
  sql: FaDatabase,
  typescript: SiTypescript,
  html: SiHtml5,
  css: SiCss3,
  springboot: SiSpringboot,
  maven: SiApachemaven,
  javalin: SiComma,
  swagger: SiSwagger,
  nltk: FaCode,
  beautifulsoup: TbLadle,
  pytorch: SiPytorch,
  tensorflow: SiTensorflow,
  keras: SiKeras,
  scikitlearn: SiScikitlearn,
  pandas: SiPandas,
  scipy: SiScipy,
  matplotlib: FaCode,
  reactjs: FaReact,
  nodejs: FaNode,
  npm: FaNpm,
  angular: FaAngular,
  sqlite: SiSqlite,
  postgresql: SiPostgresql,
  vscode: VscVscode,
  devtools: FaCode,
  git: FaGitAlt,
  bitbucket: FaBitbucket,
  jira: SiJira,
  agilescrum: GiCycle,
  confluence: SiConfluence,
  docker: FaDocker,
  kafka: SiApachekafka,
  kubernetes: SiKubernetes,
  word: FaFileWord,
  excel: FaFileExcel,
  powerpoint: FaFilePowerpoint,
  outlook: PiMicrosoftOutlookLogoFill,
  onedrive: ImOnedrive,
  teams: BsMicrosoftTeams,
  powerbi: BsFileBarGraph,
  ssrs: GiSpiralTentacle,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
